# Generated by Django 4.0.4 on 2023-08-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
        ('services', '0002_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('short_content', models.TextField()),
                ('content', models.TextField()),
                ('post_date', models.DateField(null=True)),
                ('post_time', models.TimeField(blank=True, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('end_event_date', models.DateField(null=True)),
                ('end_event_time', models.TimeField(blank=True, null=True)),
                ('approval', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('is_horizontal', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_news', to='user_app.broker')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_caterogy', to='lookup.category')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_news', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_subcaterogy', to='services.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('file', models.CharField(max_length=250, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_image', to='news.news')),
            ],
        ),
    ]
