# Generated by Django 4.0.4 on 2023-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='post_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
