# Generated by Django 4.0.4 on 2023-06-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_category'),
        ('movie', '0005_alter_streamplatform_subcategory'),
        ('lookup', '0003_remove_subcategory_broker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
