# Generated by Django 4.0.4 on 2023-06-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0003_delete_brokerservice'),
        ('lookup', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.broker')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
