# Generated by Django 4.0.4 on 2023-06-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_delete_brokerservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0003_remove_subcategory_broker_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250, null=True)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_subcategory', to='user_app.broker')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_subcategory', to='lookup.category')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_create_subcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
