# Generated by Django 4.0.4 on 2023-07-09 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_subcategory', to='user_app.broker'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_subcategory', to='lookup.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_create_subcategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerservice',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.broker'),
        ),
        migrations.AddField(
            model_name='brokerservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.category'),
        ),
    ]
