# Generated by Django 4.0.4 on 2023-06-23 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0004_delete_subcategory'),
        ('services', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_subcategory', to='lookup.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_create_subcategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
