# Generated by Django 4.0.4 on 2023-06-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_delete_subcategory'),
        ('services', '0004_brokerservice_is_active_brokerservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.category'),
        ),
    ]
