# Generated by Django 4.0.4 on 2023-06-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('image', models.CharField(max_length=250, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('end_event_date', models.DateField(null=True)),
                ('end_event_time', models.TimeField(blank=True, null=True)),
                ('post_date', models.DateField(null=True)),
                ('post_time', models.TimeField(blank=True, null=True)),
                ('end_post_date', models.DateField(null=True)),
                ('end_post_time', models.TimeField(blank=True, null=True)),
                ('notification_title', models.CharField(blank=True, max_length=250, null=True)),
                ('notification_summary', models.TextField(blank=True, null=True)),
                ('approval', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_category', to='event.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('file', models.CharField(max_length=250, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image', to='event.event')),
            ],
        ),
    ]
