# Generated by Django 4.0.4 on 2023-06-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='broker',
        ),
    ]
