# Generated by Django 4.0.4 on 2023-06-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_broker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='icon',
        ),
    ]
