# Generated by Django 4.0.4 on 2023-06-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_subcategory_sbroker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sbroker',
            new_name='broker',
        ),
    ]
