# Generated by Django 4.0.4 on 2023-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_user_subcategory_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_horizontal',
            field=models.BooleanField(default=True),
        ),
    ]
