# Generated by Django 4.0.4 on 2023-06-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_brokerservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerService',
        ),
    ]
