# Generated by Django 4.0.4 on 2023-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_accounttype_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
