# Generated by Django 4.0.4 on 2023-06-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_businesstype_broker_busines_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='busines_type',
            new_name='business_type',
        ),
    ]
