# Generated by Django 4.0.4 on 2023-06-27 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_busines_type_broker_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
