# Generated by Django 4.0.4 on 2023-06-27 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_broker_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
