# Generated by Django 4.0.4 on 2023-07-09 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        ('user_app', '0001_initial'),
        ('lookup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('sub_icon', models.TextField(blank=True, null=True)),
                ('uid_sub_icon', models.CharField(blank=True, max_length=250, null=True)),
                ('show_date', models.DateField(null=True)),
                ('time_show_date', models.TimeField(blank=True, null=True)),
                ('close_date', models.DateField(null=True)),
                ('time_close_date', models.TimeField(blank=True, null=True)),
                ('post_date', models.DateField(null=True)),
                ('post_time', models.TimeField(blank=True, null=True)),
                ('close_post_date', models.DateField(null=True)),
                ('close_post_time', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('titleNoti', models.CharField(blank=True, max_length=250, null=True)),
                ('summaryNoti', models.TextField(blank=True, null=True)),
                ('number_of_connection', models.IntegerField(blank=True, default=0, null=True)),
                ('approval', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_horizontal', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_broker', to='user_app.broker')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stream_platform_caterogy', to='lookup.category')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stream_platform_user', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_subcaterogy', to='services.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_picker', models.DateField()),
                ('time_show_date', models.TimeField()),
                ('price', models.IntegerField(default=0)),
                ('website', models.URLField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movie.streamplatform')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('name', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('file_size', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stream_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_image', to='movie.streamplatform')),
            ],
        ),
    ]
