# Generated by Django 4.0 on 2023-04-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('show_date', models.DateField(null=True)),
                ('time_show_date', models.TimeField(blank=True, null=True)),
                ('close_date', models.DateField(null=True)),
                ('time_close_date', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_picker', models.DateField()),
                ('time_show_date', models.TimeField()),
                ('price', models.IntegerField(default=0)),
                ('website', models.URLField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movie.streamplatform')),
            ],
        ),
    ]
