# Generated by Django 4.0.4 on 2023-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='notification',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
