# Generated by Django 4.0.4 on 2023-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
