# Generated by Django 4.0.4 on 2023-06-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCaterogy',
            new_name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Caterogy',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caterogy', to='lookup.category'),
        ),
    ]
