# Generated by Django 4.0.4 on 2023-04-08 15:12

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_streamplatform_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.upload_to),
        ),
    ]
