# Generated by Django 4.0.4 on 2023-06-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subcategory'),
        ('movie', '0004_streamplatform_approval_streamplatform_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='subcategory',
            field=models.ManyToManyField(null=True, related_name='stream_platform_subcaterogy', to='services.subcategory'),
        ),
    ]
