# Generated by Django 4.0.4 on 2023-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_streamplatform_active_noti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='notification',
            new_name='titleNoti',
        ),
        migrations.RemoveField(
            model_name='streamplatform',
            name='active_noti',
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='summaryNoti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
