# Generated by Django 4.0.4 on 2023-06-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_delete_brokerservice'),
        ('movie', '0005_alter_streamplatform_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_broker', to='user_app.broker'),
        ),
    ]
