# Generated by Django 4.0.4 on 2023-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_notification_streamplatform_titlenoti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
