# Generated by Django 4.0.4 on 2023-06-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_streamplatform_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='close_post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='close_post_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='post_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('file_name', models.CharField(max_length=250, null=True)),
                ('file_size', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_image', to='movie.streamplatform')),
            ],
        ),
    ]
