# Generated by Django 4.0.4 on 2023-06-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_streamplatform_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caterogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCaterogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=250, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caterogy', to='movie.caterogy')),
            ],
        ),
    ]
