# Generated by Django 4.0.4 on 2023-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_streamplatform_close_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamplatform',
            name='image',
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='sub_icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='uid_sub_icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
