# Generated by Django 4.0.4 on 2023-06-29 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0008_remove_streamplatform_image_streamplatform_sub_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stream_platform_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
