# Generated by Django 4.0.4 on 2023-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_multipleimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='name',
            field=models.TextField(),
        ),
    ]
